### ISSUE TITLE
Switch在内部边缘点击无法正常切换

### ISSUE THREAD

**Issue by BboyAwey** [DouyinFE/semi-design#992] opened 2022-07-26 06:27 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which Component

Switch

### Semi Version

V2

### Current Behavior

https://user-images.githubusercontent.com/15099804/180938070-10c4fccc-2631-475f-b809-8d395425dd7e.mov

### Expected Behavior

可以正常切换

### Steps To Reproduce

1. 点击Switch中间区域内部靠近下沿的边缘
2. 可以观察到原点有形变动画，但是无法切换位置

### Environment

```markdown
- OS:
- browser:
```

**Comment by linjunc** [comment] 2022-07-31 04:57
I have found the cause of this bug, it will be fixed soon

**Closed** 2022-08-01 07:21 UTC
Labels: bug

**Comment by pointhalo** [comment] 2022-08-05 10:49
fix 2.16.1

![image](https://user-images.githubusercontent.com/88709023/183062347-d470007c-cc3c-4689-9e4f-19c9ffb1811f.png)
